### ISSUE TITLE
Serving from 'docs/' Folder to Include Site Sources

### ISSUE THREAD

**Issue by tajmone** [pdml-lang/pdml-lang.github.io#1]
I noticed that you're serving the GHPages directly from the repo root.

You might consider to switch to using the `docs/` folder instead, which would allow the rest of the repository to contain the PML source files, assets, etc. to build the static HTML website, instead.

While this wouldn't affect how the online website is viewed, it would allow users to contribute to it by submitting changes to the PML sources, or other assets. E.g. the repository could contain Sass sources to generate the stylesheets, and use Rake to manage building the website, its assets and any required tests and validation.

The PML source repositories for the various docs (specs, examples, articles, etc.) could be integrate via Git submodules, which would make working with website sources a very smooth experience.

You'd still have the same static HTML contents the `docs/` folder, but with the benefits of having all the source files in the same repository.

**Comment by pdml-lang** [comment]
> You might consider to switch to using the docs/ folder

Done. Thanks for the tip.

**Comment by pdml-lang** [comment]
The [pdml-lang.github.io](https://github.com/pdml-lang/pdml-lang.github.io) repository now contains all source files, as well as [instructions](https://github.com/pdml-lang/pdml-lang.github.io#readme) to build the [PDML website](https://pdml-lang.dev/).

I decided to not use Git submodules, because it is easier to maintain the website if everything is stored in one repo.

I now plan to:

1. Transfer all issues and discussions from the [basic-specification](https://github.com/pdml-lang/basic-specification) repo to the [pdml-lang.github.io](https://github.com/pdml-lang/pdml-lang.github.io) repo. Other existing repos related to PDML _documentation_ don't have issues or discussion entries.

1. Remove all existing repos related to PDML _documentation_, because their content is now stored in [pdml-lang.github.io](https://github.com/pdml-lang/pdml-lang.github.io).

Is there a better way to keep the issues and discussions?

I intend to do the same changes in the [PML repos](https://github.com/pml-lang).

**Comment by pml-lang** [comment]
> in the current situation it probably makes more sense to keep things simple and store all the material under a single umbrella repository. If in the future a real need arises to justify sub-moduling the sources to facilitate other projects, you can always do it ...

Exactly! At the moment I really want to keep it simple and start with a single repo for the PDML and PML websites.

> enabling the new Dashboard features

I'll do that. Thanks for the tip and the time you took to describe the pros and cons of GitHub submodules.
